bicycles = ['trek','cannondale','redline','specialized']
print(bicycles)
print()
print(bicycles[0])
print()
print(bicycles[0].title())
print()
print(bicycles[-1].upper())
print()
motorcycles = ['honda', 'yamaha', 'suzuki']
print(motorcycles)
print()
motorcycles.append('ducati')
print(motorcycles)
print()
motorcycles.insert(0,'ducati')
print(motorcycles)
print()
del motorcycles[0]
print(motorcycles)
print()
popped_motorcycle = motorcycles.pop()
print(popped_motorcycle)
print()
first_owned = motorcycles.pop(0)
print(first_owned)
print()
motorcycles.remove('yamaha')
print(motorcycles)
print()
cars = ['bmw', 'audi', 'toyota', 'subaru']
cars.sort()
print(cars)
print()
cars.sort(reverse=True)
print(cars)
print()
print(sorted(cars))
print()
cars = ['bmw', 'audi', 'toyota', 'subaru']
cars.reverse()
print(cars)
